allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - msw
  - prisma
  - sharp
  - unrs-resolver
